:PROPERTIES:
:UNNUMBERED: t
:END:
#+options: toc:nil stat:nil todo:nil
* Bootstrapping an engineering organisation
I've written (and continue to write!) this blog post series over the course of many years. It is based on my experiences at various companies that have had extremely good working practices. Much of what I write about is based on my observations at these companies, so credit goes to their employees!

My main observation in these companies has been: if you get things right early-on building an engineering organisation, it can set you up for success later on in the future. This series of blog post is about some of the essential ingredients to consider when bootstrapping an engineering organisation, with some deep-dives into some of these ingredients.

I hope you find it interesting!

/12th March 2026/

-----

1. [[file:bootstrapping-an-engineering-organisation.org][Bootstrapping a successful engineering organisation]]
2. [[file:2023-05-03-secrets-management-in-build-and-deployment-pipelines.md][Secrets management in build & deployment pipelines]]
3. [[file:2023-05-17-decision-making-and-design.md][Decision making & design]]
4. [[file:2023-11-07-securing-environment-access.md][Securing environment access]]
5. Documentation /(in draft)/
6. Testing /(in draft)/
7. Secrets management in applications /(in draft)/
8. Incident response /(in draft)/
9. [[file:2026-03-12-getting-observability-right.md][Observability]]
